# basic options
title: Leo's personal hub
author: Leo
email: leolee5633@gmail.com
description: A small website to share my ideas and thoughts.


# build settings
markdown: kramdown
theme: jekyll-theme-cayman
